android.overridePathCheck=true
storePassword=admin123
keyAlias=myreleasekey
keyPassword=admin123
android.useAndroidX=true
android.overridePathCheck=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.refreshDependencies=true
org.gradle.logging.level=lifecycle
android.enableR8.fullMode=true
